---
# tasks file for sslh (Ubuntu specific)

- name: Install sslh packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ sslh_packages }}"
  tags:
    - sslh
